stages:
 - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

upload:
 stage: deploy
 only:
   - master
 image: ubuntu
 before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'

   - eval $(ssh-agent -s)

   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
   - echo "$SSH_PRIVATE_KEY"

   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
 script:
   - ssh $CI_USER@$SERVER_IP sudo systemctl stop wishwish
   - scp -vrC ./ $CI_USER@$SERVER_IP:$HOST_PATH/
   - ssh -t $CI_USER@$SERVER_IP "cd wishwish; yarn"
   - ssh $CI_USER@$SERVER_IP sudo systemctl start wishwish
 only:
   - master
