version: '3'

services:
  api:
    image: mhart/alpine-node:10.8
    depends_on:
    - mongodb
    volumes:
    - .:/home/node
    working_dir: /home/node
    command: yarn start
    env_file:
      - ./docker/.env
    ports:
    - "3000:3000"

  mongodb:
    image: mvertes/alpine-mongo:4.0.0-0
    volumes:
    - mongodb:/data/db/
    ports:
      - "27017:27017"

  proxy:
    image: nginx:stable-alpine
    depends_on:
    - api
    volumes:
    - ./docker/cert.pem:/etc/nginx/ssl/nginx.crt:ro
    - ./docker/key.pem:/etc/nginx/ssl/nginx.key:ro
    - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    command: mkdir -p /var/www/wshlst/uploads
    ports:
    - "3333:80"
    - "4444:443"

volumes:
  mongodb:
